#!/bin/sh

# Color aliases
#alias ls="ls -hN --color=auto --group-directories-first"
#alias ip="ip -color=auto"
#alias diff="diff --color=auto"
#alias grep="grep --color=auto"

# Custom aliases
alias ed="ed -p '*'"
alias yt-dlp="yt-dlp --embed-metadata -i"
alias irssi="irssi --home=${XDG_CONFIG_HOME:-$HOME/.config}/irssi/"
