#!/bin/sh

# Custom aliases
alias ed="ed -p '*'"
alias yt-dlp="yt-dlp --embed-metadata -i"
alias irssi="irssi --home=${XDG_CONFIG_HOME:-$HOME/.config}/irssi/"
alias locate="plocate"
alias updatedb="doas updatedb"
alias otp="pass otp"
alias ffmpeg="ffmpeg -hide_banner"
alias adb='HOME="$XDG_DATA_HOME/android" adb'
alias sxiv="nsxiv"
