#!/bin/zsh

# My zsh profile for the z-shell

# Add scripts to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Program vars
export BROWSER="firefox"
export EDITOR="nvim"
export TERMINAL="st"
export READER="zathura"

# sfeed vars
export SFEED_SOURCE="${XDG_CONFIG_HOME:-$HOME/.config}/sfeed/sfeedrc"
export SFEED_FEEDS="${XDG_DATA_HOME:-$HOME/.local/share}/sfeed/feeds"

# XDG dirs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export GIT_CONFIG_GLOBAL="${XDG_CONFIG_HOME:-$HOME/.config}/git/gitconfig"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
export PARALLEL_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/parallel"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"

# Other settings
export MOZ_USE_XINPUT2="1"	# Mozilla smooth scrolling
export PRINTER="Canon_MF642C_643C_644C_UFR_II"
