#!/bin/sh

# My xprofile

# Set wallpaper
wallpapers &

# Allows notfications
dunst &

# Add compositing
xcompmgr &

# Hide mouse cursor after 3 sec.
unclutter-xfixes -idle 3 -root &

# Start dwmblocks
dwmblocks &

# Start screen locker
xautolock -locker slock -time 30 &

# Start pipewire
export $(dbus-launch)
/usr/libexec/pipewire-launcher &
