#!/bin/sh

# My xprofile

# Set wallpaper
wallpapers &

# Allows notfications
dunst &

# Add compositing
xcompmgr &

# Hide mouse cursor after 3 sec.
unclutter-xfixes -idle 3 -root &

# Start dwmblocks
dwmblocks &

# Start screen locker
xautolock -locker slock -time 30 &

# Start pulseaudio that doesn't quit on idle
#pidof -s runit &&
#	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
